name: Build
description: Build application with Maven and create a new Docker image

inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "./src/main/docker/Dockerfile.jvm"
  image_name:
    description: 'Name of the Docker image'
    required: true
    default: 'my-docker-image'
  tag_name:
    description: 'Tag to apply to the Docker image'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set TAG and DOCKER_IMAGE_NAME environment variables
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
        echo "DOCKER_IMAGE_NAME=${{ inputs.image_name }}:${{ env.TAG }}" >> $GITHUB_ENV
      shell: bash

    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_NAME }} -f ${{ inputs.dockerfile_path }} .
      shell: bash
